config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'spots_vtts/index'
  root to: 'pages#home'
  get 'pages/spots'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :comfirm_email
    end
  end
  resources :spots_vtts, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spots_vtt.rb
class SpotsVtt < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
  validates :name, :start, :difficulty, :city, :distance, :alt_min, :alt_max, :elevation_gain, :latitude, :longitude, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :pseudo, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # add custom params for devise
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[pseudo email password password_confirmation])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @user = User.all
  end

  def spots; end
end

app/controllers/spots_vtts_controller.rb
class SpotsVttsController < ApplicationController
  def index
    @spots_vtts = SpotsVtt.all
    @markers = @spots_vtts.map do |spots_vtt|
      {
        lat: spots_vtt.latitude,
        lng: spots_vtt.longitude
      }
    end
  end

  def show
    @spots_vtt = SpotsVtt.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spots_vtts_helper.rb
module SpotsVttsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotPlaces</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "shared/navbar" %>
   
    <%= yield %>

<div id="wrapper"></div>
  <%= render "shared/flashes" %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
    <div class="align-big-title">
       <h1 class="big-title"> <%= link_to pages_spots_path do %> DISCOVER THE WORLD <i class="fas fa-arrow-right"> </i> <% end %> </h1>
    </div>
</div>

app/views/pages/spots.html.erb
<div class="container-fluid">
    <h1> All spots </h1>
    <h1><%= link_to "vtt", spots_vtts_path %></h1>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Footer Content</h5>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
          molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
          voluptatem veniam, est atque cumque eum delectus sint!
        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled mb-0">
          <li class="link-footer">
            <a href="#!">Link 1</a>
          </li>
          <li class="link-footer">
            <a href="#!">Link 2</a>
          </li>
          <li class="link-footer">
            <a href="#!">Link 3</a>
          </li>
          <li class="link-footer">
            <a href="#!">Link 4</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    <p class="align-middle"> SpotPlaces &copy; <%= Time.now.year %>. All Rights Reserved.</p>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/spots_vtts/index.html.erb
<div class=container-fluid>
    <h1>SpotsVtts#index</h1>
       <p><%= @markers %></p>
    <div class="container">
      <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
        <% @spots_vtts.each do |spot| %>
            <div class="card-spot">
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
                <div class="card-spot-infos">
                    <h2><%= link_to spot.name, spots_vtt_path(spot) %></h2> 
                    <p>Product description with <strong>relevant info</strong> only.</p>
                </div>
            </div>
        <% end %>
    </div>
</div>  

app/views/spots_vtts/show.html.erb
<div class="container-fluid">
    <div class="name-spot-vtt">
        <h1><%= @spots_vtt.name %></h1>
    </div>

    <div class="container">
  

    <table class="table table-bordered">
  <tr>
    <th>Difficulté:</th>
    <td><%= @spots_vtt.difficulty %></td>
  </tr>
  <tr>
    <th>Ville:</th>
    <td><%= @spots_vtt.city %> </td>
  </tr>
  <tr>
    <th>Départ:</th>
    <td><%= @spots_vtt.start %></td>
  </tr>
    <tr>
    <th>Distance total:</th>
    <td><%= @spots_vtt.distance %> km</td>
  </tr>
    <tr>
    <th>Altitude max:</th>
    <td><%= @spots_vtt.alt_max %> M</td>
  </tr>
    <tr>
    <th>Denivelé:</th>
     <td><%= @spots_vtt.elevation_gain %> M</td>
  </tr>
</table>
<p>latitude : <%= @spots_vtt.latitude %></p>
<p>longitude : <%= @spots_vtt.longitude %></p>

</div>

</div>